// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqL3duo1JdfF5VnXTNaiX1D4nH0QmMTbM',
    appId: '1:824867666101:web:b350ca2a92129b372be6fc',
    messagingSenderId: '824867666101',
    projectId: 'orbeit-613',
    authDomain: 'orbeit-613.firebaseapp.com',
    storageBucket: 'orbeit-613.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB42dTHndcBD4X3-biVQxXlgc9JhoLH5z4',
    appId: '1:824867666101:android:da955a9c3fbc3e282be6fc',
    messagingSenderId: '824867666101',
    projectId: 'orbeit-613',
    storageBucket: 'orbeit-613.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqy_B-4FUG5VEIgx7_wYP1yL8hYE1qJ-Y',
    appId: '1:824867666101:ios:6f96e48ce8a2f92d2be6fc',
    messagingSenderId: '824867666101',
    projectId: 'orbeit-613',
    storageBucket: 'orbeit-613.firebasestorage.app',
    iosBundleId: 'com.orbeit.app',
  );
}
